### ISSUE TITLE
Nav is really tall on mobile Safari

### ISSUE THREAD

**Issue by jeremy-deutsch** [solidjs/solid-site#77]
On my iPhone, the site's navbar takes up a large amount of the screen, as seen in the video below. Unfortunately I can't submit a fix, because I can't reproduce this using Chrome or Firefox on my Windows PC.

https://user-images.githubusercontent.com/13303900/124178134-0cba7e00-da66-11eb-9fd3-d8eb84123fa8.MOV

**Comment by davedbase** [comment]
Thanks, we'll address this asap.

**Comment by davedbase** [comment]
@jeremy-deutsch mind confirming that the issue is resolved on your end?

**Comment by jeremy-deutsch** [comment]
It's not resolved, sorry. The navbar looks the same. Are you not able to test on Safari either?

**Comment by davedbase** [comment]
Indeed I can and have. It seemed resolved to me but I always have an end user confirm before closing the issue. See the below screen:

![image](https://user-images.githubusercontent.com/1168397/124367287-e80c0500-dc23-11eb-9f0d-a7676d4560f6.png)

Can you try a hard refresh? I suspect the service worker might not be kicking in with an update? It should be automatic though.

**Comment by jeremy-deutsch** [comment]
Still not showing - I'll try again later to see if it changed

**Comment by davedbase** [comment]
I can't seem to replicate this nor have I had a few others who've tested been able to. Thanks for reporting.
